version: "3"

dotenv: [.env]

includes:
  core:
    taskfile: ./core/tasks.yml
    dir: ./core

  app:
    taskfile: ./app/tasks.yml
    dir: ./app

tasks:
  default:
    silent: true
    desc: List all available tasks
    cmds:
      - task --list-all --sort none

  format:
    desc: Format source code
    cmds:
      - task: format:clang
      - task: core:format:cargo
      - task: app:format:qml

  format:clang:
    desc: Format source code with clang-format
    internal: true
    preconditions:
      - sh: command -v clang-format
        msg: clang-format is not available in PATH
    cmds:
      - >-
        git ls-files -z
        --cached
        --others
        --exclude-standard
        --
        "*.c" "*.cc" "*.cpp" "*.cxx"
        "*.h" "*.hh" "*.hpp" "*.hxx"
        "*.m" "*.mm"
        | xargs -0 clang-format -i
