[workspace]
resolver = "3"
members = ["ward-core","ward-realm", "ward-realm-vz"]

[workspace.package]
version = "0.1.0+1"
edition = "2024"
publish = false

[workspace.dependencies]
# workspace crates
ward-core = { path = "ward-core" }
ward-realm = { path = "ward-realm" }
ward-realm-vz = { path = "ward-realm-vz" }

# third-party crates
anyhow = "1"
cc = "1"
