[workspace]
resolver = "3"
members = [
    "ward-cli",
    "ward-codex",
    "ward-codex-test-support",
    "ward-core",
    "ward-realm",
    "ward-realm-vz",
    "ward-runtime",
]

[workspace.package]
version = "0.1.0+1"
edition = "2024"
publish = false
license = "GPL-3.0-or-later"

[workspace.dependencies]
# workspace crates
ward-cli = { path = "ward-cli" }
ward-codex = { path = "ward-codex" }
ward-codex-test-support = { path = "ward-codex-test-support" }
ward-core = { path = "ward-core" }
ward-realm = { path = "ward-realm" }
ward-realm-vz = { path = "ward-realm-vz" }
ward-runtime = { path = "ward-runtime" }

# third-party crates
anyhow = "1"
cc = "1"
clap = "4"
serde = "1"
serde_json = "1"
serde_with = "3"
thiserror = "2"
tokio = { version = "1.53", features = ["full"] }
tokio-util = { version = "0.7", features = ["rt"] }
uuid = "1"
prost = "0.14"
prost-build = "0.14"
