// Copyright (C) 2026 Xiangsong Zeng
// SPDX-License-Identifier: GPL-3.0-or-later

// clang-format off


#ifndef WARD_CORE_H
#define WARD_CORE_H

/* Generated with cbindgen:0.29.4 */

/* Generated by `task xtask:bindings:generate`. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// A Codex turn mode passed through Ward Core's private C interface.
typedef enum WardCodexTurnMode {
    WardCodexTurnModeDefault = 0,
    WardCodexTurnModePlan = 1,
} WardCodexTurnMode;

// A Codex turn permission preset passed through Ward Core's private C
// interface.
typedef enum WardCodexPermissionPreset {
    WardCodexPermissionPresetInherit = 0,
    WardCodexPermissionPresetRequestApproval = 1,
    WardCodexPermissionPresetReadOnly = 2,
} WardCodexPermissionPreset;

// A Codex turn attachment kind passed through Ward Core's private C
// interface.
typedef enum WardCodexTurnAttachmentKind {
    WardCodexTurnAttachmentKindLocalImage = 0,
    WardCodexTurnAttachmentKindLocalAudio = 1,
    WardCodexTurnAttachmentKindMention = 2,
} WardCodexTurnAttachmentKind;

// A source syntax accepted by Ward Core's app-only markup interface.
typedef enum WardMarkupSourceFormat {
    WardMarkupSourceFormatPlainText = 0,
    WardMarkupSourceFormatMarkdown = 1,
} WardMarkupSourceFormat;

// A Realm lifecycle state passed through Ward Core's private C interface.
typedef enum WardRealmState {
    WardRealmStateStopped = 0,
    WardRealmStateRunning = 1,
    WardRealmStatePaused = 2,
    WardRealmStateError = 3,
    WardRealmStateStarting = 4,
    WardRealmStatePausing = 5,
    WardRealmStateResuming = 6,
    WardRealmStateStopping = 7,
    WardRealmStateSaving = 8,
    WardRealmStateRestoring = 9,
    WardRealmStateSuspended = 10,
} WardRealmState;

// An opaque borrowed serialized payload passed through Ward Core's private C interface.
typedef struct WardBuffer WardBuffer;

// An opaque Codex execution target passed through Ward Core's private C
// interface.
//
// An execution target hides how independent Codex app-server connections are
// opened. A host target starts a local executable; other target adapters can
// provide the same connection source without changing observers.
typedef struct WardCodexExecutionTarget WardCodexExecutionTarget;

// An opaque asynchronous Codex history observer passed through Ward Core's
// private C interface.
typedef struct WardCodexHistoryObserver WardCodexHistoryObserver;

// An owned immediate-call error passed through Ward Core's private C
// interface.
//
// A caller that receives a non-null error owns it and must destroy it with
// [`ward_core_error_destroy`]. Final failures for accepted asynchronous
// operations are delivered through their event callback instead of this type.
typedef struct WardError WardError;

// An opaque owned serialized payload returned through Ward Core's app-only interface.
typedef struct WardOwnedBuffer WardOwnedBuffer;

// An opaque realm handle passed through Ward Core's private C interface.
typedef struct WardRealm WardRealm;

// An opaque owner of Ward Core's process-wide asynchronous runtime.
typedef struct WardRuntime WardRuntime;

// A BLAKE3-256 digest passed through Ward Core's private C interface.
typedef struct WardBlake3Digest {
    uint8_t bytes[32];
} WardBlake3Digest;

// The result of dispatching process arguments through Ward's embedded CLI.
typedef struct WardCliResult {
    bool handled;
    int exit_code;
} WardCliResult;

// Receives borrowed serialized Codex history events.
//
// The callback may run on any Ward runtime thread and may run before
// [`ward_core_codex_history_observer_open`] returns. `event` remains valid
// only until the callback returns, and `context` must remain valid until
// [`ward_core_codex_history_observer_destroy`] returns. If opening fails, no
// callback occurs after the open function returns. The callback must not
// destroy its observer and must not unwind across the C interface.
typedef void (*WardCodexHistoryEventCallback)(void *context, const struct WardBuffer *event);

// One typed local attachment borrowed through Ward Core's private C interface.
typedef struct WardCodexTurnAttachment {
    enum WardCodexTurnAttachmentKind kind;
    const char *name;
    const char *path;
} WardCodexTurnAttachment;

// A lifecycle snapshot passed through Ward Core's private C interface.
typedef struct WardRealmStatus {
    enum WardRealmState state;
    bool can_start;
    bool can_pause;
    bool can_resume;
    bool can_request_stop;
    bool can_force_stop;
    bool can_suspend;
    bool can_restore;
    bool can_discard_saved_state;
} WardRealmStatus;

// A borrowed Realm lifecycle event passed to a Realm callback.
//
// The event and optional error message remain valid only until the callback
// returns. The callback must copy anything it needs to retain.
typedef struct WardRealmEvent {
    struct WardRealmStatus status;
    const char *error_message;
} WardRealmEvent;

// Receives borrowed Realm lifecycle events.
//
// The callback may run on any thread and may run before
// [`ward_core_realm_open`] returns. `context` must remain valid until
// [`ward_core_realm_destroy`] returns. The callback must not destroy its Realm
// handle and must not unwind across the C interface.
typedef void (*WardRealmEventCallback)(void *context, const struct WardRealmEvent *event);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Computes the BLAKE3-256 digest of a file on the calling thread.
//
// # Safety
//
// `path` must point to a NUL-terminated UTF-8 path. `output_digest` must be
// writable. `output_error`, when non-null, must be writable.
bool ward_core_blake3_hash_file(const char *path,
                                struct WardBlake3Digest *output_digest,
                                struct WardError **output_error);

// Returns the borrowed bytes in a serialized Ward buffer.
//
// The returned pointer remains valid for the lifetime of the borrowed buffer.
//
// # Safety
//
// `buffer` must be null or a valid borrowed buffer supplied by Ward Core.
const uint8_t *ward_core_buffer_data(const struct WardBuffer *buffer);

// Returns the number of bytes in a serialized Ward buffer.
//
// # Safety
//
// `buffer` must be null or a valid borrowed buffer supplied by Ward Core.
size_t ward_core_buffer_size(const struct WardBuffer *buffer);

// Dispatches process arguments through Ward's embedded CLI.
//
// An invocation without arguments is left unhandled so the caller can start
// its graphical interface. Every other invocation is handled as a CLI request
// and returns the corresponding process exit code.
//
// # Safety
//
// `argv` must contain `argc` pointers to NUL-terminated strings when `argc`
// is positive. The strings must remain valid until this function returns.
struct WardCliResult ward_core_cli_try_run(int argc, char **argv);

// Creates a host-backed Codex execution target.
//
// The target starts `executable` in `app-server --stdio` mode whenever an
// observer needs a new Codex connection. Creating the target does not start a
// process.
//
// # Safety
//
// `executable` must point to a non-empty NUL-terminated string.
// `output_error`, when non-null, must be writable.
struct WardCodexExecutionTarget *ward_core_codex_execution_target_create_host(const char *executable,
                                                                              struct WardError **output_error);

// Destroys a Codex execution target.
//
// Observers clone the target's connection source when they are opened, so an
// execution target may be destroyed before observers created from it.
//
// # Safety
//
// `target` must be null or a live handle returned by a Codex execution-target
// factory, and ownership may be transferred only once.
void ward_core_codex_execution_target_destroy(struct WardCodexExecutionTarget *target);

// Attempts to acquire exclusive writing access for one persisted thread.
//
// The asynchronous result is emitted as a thread write-state event. A
// successful acquisition remains active until it is released, another thread
// is selected, or the observer is destroyed.
//
// A `true` return means the command was accepted; its final outcome is
// delivered through the Codex event callback. A `false` return means
// immediate rejection, and `output_error` receives an owned error when
// non-null.
//
// # Safety
//
// `observer` must point to a live handle returned by
// [`ward_core_codex_history_observer_open`]. `thread_id` must point to a
// NUL-terminated string. `output_error`, when non-null, must be writable.
bool ward_core_codex_history_observer_acquire_write_async(struct WardCodexHistoryObserver *observer,
                                                          const char *thread_id,
                                                          struct WardError **output_error);

// Moves one active persisted Codex thread into archived history.
//
// The resulting active-history snapshot is emitted asynchronously.
//
// A `true` return means the command was accepted; its final outcome is
// delivered through the Codex event callback. A `false` return means
// immediate rejection, and `output_error` receives an owned error when
// non-null.
//
// # Safety
//
// `observer` must point to a live handle returned by
// [`ward_core_codex_history_observer_open`]. `thread_id` must point to a
// NUL-terminated string. `output_error`, when non-null, must be writable.
bool ward_core_codex_history_observer_archive_thread_async(struct WardCodexHistoryObserver *observer,
                                                           const char *thread_id,
                                                           struct WardError **output_error);

// Continues one interrupted persisted Codex thread without adding input.
//
// The observer uses its previously acquired writer and emits ordered
// conversation updates until the turn completes.
//
// A `true` return means the command was accepted; its final outcome is
// delivered through the Codex event callback. A `false` return means
// immediate rejection, and `output_error` receives an owned error when
// non-null.
//
// # Safety
//
// `observer` must point to a live handle returned by
// [`ward_core_codex_history_observer_open`]. `thread_id` must point to a
// NUL-terminated string. `model` and `reasoning_effort` use the same optional
// string convention as [`ward_core_codex_history_observer_start_turn_async`].
// `turn_mode` and `permission_preset` must use values declared by the private
// C interface. `output_error`, when non-null, must be writable.
bool ward_core_codex_history_observer_continue_turn_async(struct WardCodexHistoryObserver *observer,
                                                          const char *thread_id,
                                                          const char *model,
                                                          const char *reasoning_effort,
                                                          enum WardCodexTurnMode turn_mode,
                                                          enum WardCodexPermissionPreset permission_preset,
                                                          struct WardError **output_error);

// Stops and destroys a Codex history observer.
//
// This function waits for any in-flight read and callback to finish before it
// returns. It must not be called from the observer callback itself or from a
// worker thread belonging to the observer's Ward runtime.
//
// # Safety
//
// `observer` must be null or a live handle returned by
// [`ward_core_codex_history_observer_open`], and ownership may be transferred
// only once.
void ward_core_codex_history_observer_destroy(struct WardCodexHistoryObserver *observer);

// Forks one active, loaded, and idle persisted Codex thread through a
// completed turn.
//
// The asynchronous result is emitted as either a thread-forked event carrying
// the new conversation or a thread-fork-error event for the source thread.
//
// A `true` return means the command was accepted; its final outcome is
// delivered through the Codex event callback. A `false` return means
// immediate rejection, and `output_error` receives an owned error when
// non-null.
//
// # Safety
//
// `observer` must point to a live handle returned by
// [`ward_core_codex_history_observer_open`]. `thread_id` and `last_turn_id`
// must point to NUL-terminated strings. `output_error`, when non-null, must be
// writable.
bool ward_core_codex_history_observer_fork_thread_async(struct WardCodexHistoryObserver *observer,
                                                        const char *thread_id,
                                                        const char *last_turn_id,
                                                        struct WardError **output_error);

// Requests interruption of the selected thread's active Codex turn.
//
// The interruption is asynchronous. Runtime and turn-completion events report
// the eventual state.
//
// A `true` return means the command was accepted; its final outcome is
// delivered through the Codex event callback. A `false` return means
// immediate rejection, and `output_error` receives an owned error when
// non-null.
//
// # Safety
//
// `observer` must point to a live handle returned by
// [`ward_core_codex_history_observer_open`]. `thread_id` must point to a
// NUL-terminated string. `output_error`, when non-null, must be writable.
bool ward_core_codex_history_observer_interrupt_turn_async(struct WardCodexHistoryObserver *observer,
                                                           const char *thread_id,
                                                           struct WardError **output_error);

// Starts a background observer for Codex model metadata and persisted history.
//
// The callback receives a borrowed serialized event buffer from the observer
// thread. Its context must remain valid until
// [`ward_core_codex_history_observer_destroy`] returns.
//
// # Safety
//
// `runtime` must point to a live Ward runtime that outlives the returned
// observer. `execution_target` must point to a live Codex execution target
// for the duration of this call. `callback` must be a valid function pointer.
// `output_error`, when non-null, must be writable.
struct WardCodexHistoryObserver *ward_core_codex_history_observer_open(const struct WardRuntime *runtime,
                                                                       const struct WardCodexExecutionTarget *execution_target,
                                                                       WardCodexHistoryEventCallback callback,
                                                                       void *callback_context,
                                                                       struct WardError **output_error);

// Requests an immediate history refresh while preserving the observer.
//
// A `true` return means the command was accepted; its final outcome is
// delivered through the Codex event callback. A `false` return means
// immediate rejection, and `output_error` receives an owned error when
// non-null.
//
// # Safety
//
// `observer` must point to a live handle returned by
// [`ward_core_codex_history_observer_open`]. `output_error`, when non-null,
// must be writable.
bool ward_core_codex_history_observer_refresh_async(struct WardCodexHistoryObserver *observer,
                                                    struct WardError **output_error);

// Releases writing access previously acquired for one persisted thread.
//
// The release is asynchronous. Its completion is emitted as a thread
// write-state event.
//
// A `true` return means the command was accepted; its final outcome is
// delivered through the Codex event callback. A `false` return means
// immediate rejection, and `output_error` receives an owned error when
// non-null.
//
// # Safety
//
// `observer` must point to a live handle returned by
// [`ward_core_codex_history_observer_open`]. `thread_id` must point to a
// NUL-terminated string. `output_error`, when non-null, must be writable.
bool ward_core_codex_history_observer_release_write_async(struct WardCodexHistoryObserver *observer,
                                                          const char *thread_id,
                                                          struct WardError **output_error);

// Renames one persisted Codex thread.
//
// Updated thread and conversation snapshots are emitted asynchronously after
// the rename succeeds.
//
// A `true` return means the command was accepted; its final outcome is
// delivered through the Codex event callback. A `false` return means
// immediate rejection, and `output_error` receives an owned error when
// non-null.
//
// # Safety
//
// `observer` must point to a live handle returned by
// [`ward_core_codex_history_observer_open`]. `thread_id` and `name` must point
// to NUL-terminated strings. `output_error`, when non-null, must be writable.
bool ward_core_codex_history_observer_rename_thread_async(struct WardCodexHistoryObserver *observer,
                                                          const char *thread_id,
                                                          const char *name,
                                                          struct WardError **output_error);

// Sends one structured response to a pending Codex interaction.
//
// A `true` return means the command was accepted; its final outcome is
// delivered through the Codex event callback. A `false` return means
// immediate rejection, and `output_error` receives an owned error when
// non-null.
//
// # Safety
//
// `observer` must point to a live handle returned by
// [`ward_core_codex_history_observer_open`]. `response_data` must point to
// `response_size` readable bytes containing a serialized
// `PendingInteractionResponse`. `output_error`, when non-null, must be
// writable.
bool ward_core_codex_history_observer_resolve_interaction_async(struct WardCodexHistoryObserver *observer,
                                                                const uint8_t *response_data,
                                                                size_t response_size,
                                                                struct WardError **output_error);

// Restores one archived persisted Codex thread to active history.
//
// The resulting archived-history snapshot is emitted asynchronously.
//
// A `true` return means the command was accepted; its final outcome is
// delivered through the Codex event callback. A `false` return means
// immediate rejection, and `output_error` receives an owned error when
// non-null.
//
// # Safety
//
// `observer` must point to a live handle returned by
// [`ward_core_codex_history_observer_open`]. `thread_id` must point to a
// NUL-terminated string. `output_error`, when non-null, must be writable.
bool ward_core_codex_history_observer_restore_thread_async(struct WardCodexHistoryObserver *observer,
                                                           const char *thread_id,
                                                           struct WardError **output_error);

// Enables or suspends periodic persisted-history polling.
//
// Disabling polling preserves the observer, its selected thread, live writer
// events, and explicit operations. Re-enabling polling schedules an immediate
// thread-list refresh and refreshes the selected conversation when present.
//
// A `true` return means the command was accepted. A `false` return means
// immediate rejection, and `output_error` receives an owned error when
// non-null.
//
// # Safety
//
// `observer` must point to a live handle returned by
// [`ward_core_codex_history_observer_open`]. `output_error`, when non-null,
// must be writable.
bool ward_core_codex_history_observer_set_polling_enabled_async(struct WardCodexHistoryObserver *observer,
                                                                bool enabled,
                                                                struct WardError **output_error);

// Switches the observer between active and archived persisted history.
//
// The next successful list read is emitted as a scope-tagged authoritative
// snapshot.
//
// A `true` return means the command was accepted; its final outcome is
// delivered through the Codex event callback. A `false` return means
// immediate rejection, and `output_error` receives an owned error when
// non-null.
//
// # Safety
//
// `observer` must point to a live handle returned by
// [`ward_core_codex_history_observer_open`]. `output_error`, when non-null,
// must be writable.
bool ward_core_codex_history_observer_show_archived_async(struct WardCodexHistoryObserver *observer,
                                                          bool archived,
                                                          struct WardError **output_error);

// Starts and observes one persisted Codex thread.
//
// The asynchronous result is emitted as either a thread-started event or a
// thread-start-error event. A successful start also grants writing access and
// makes the new thread the observer's selected thread.
//
// A `true` return means the command was accepted; its final outcome is
// delivered through the Codex event callback. A `false` return means
// immediate rejection, and `output_error` receives an owned error when
// non-null.
//
// # Safety
//
// `observer` must point to a live handle returned by
// [`ward_core_codex_history_observer_open`]. `working_directory` must point to
// a NUL-terminated string. `output_error`, when non-null, must be writable.
bool ward_core_codex_history_observer_start_thread_async(struct WardCodexHistoryObserver *observer,
                                                         const char *working_directory,
                                                         struct WardError **output_error);

// Starts one turn on the selected persisted Codex thread.
//
// The observer uses its previously acquired writer and emits ordered
// conversation updates until the turn completes.
//
// A `true` return means the command was accepted; its final outcome is
// delivered through the Codex event callback. A `false` return means
// immediate rejection, and `output_error` receives an owned error when
// non-null.
//
// # Safety
//
// `observer` must point to a live handle returned by
// [`ward_core_codex_history_observer_open`]. `thread_id` and `prompt` must
// point to NUL-terminated strings. The prompt and attachments must contain at
// least one turn input item. When `attachment_count` is nonzero,
// `attachments` must point to that many attachment records. Every record must
// contain NUL-terminated `name` and `path` strings and a declared attachment
// kind.
// `model` may be null to preserve the thread's active model; otherwise it must
// point to a non-empty NUL-terminated string. `reasoning_effort` follows the
// same convention for the thread's active reasoning effort. `turn_mode` and
// `permission_preset` must use values declared by the private C interface.
// `output_error`, when non-null, must be writable.
bool ward_core_codex_history_observer_start_turn_async(struct WardCodexHistoryObserver *observer,
                                                       const char *thread_id,
                                                       const char *prompt,
                                                       const struct WardCodexTurnAttachment *attachments,
                                                       size_t attachment_count,
                                                       const char *model,
                                                       const char *reasoning_effort,
                                                       enum WardCodexTurnMode turn_mode,
                                                       enum WardCodexPermissionPreset permission_preset,
                                                       struct WardError **output_error);

// Adds typed guidance to the selected thread's expected active Codex turn.
//
// The asynchronous result is emitted as either a turn-steered event or a
// turn-steer-error event.
//
// A `true` return means the command was accepted; its final outcome is
// delivered through the Codex event callback. A `false` return means
// immediate rejection, and `output_error` receives an owned error when
// non-null.
//
// # Safety
//
// `observer` must point to a live handle returned by
// [`ward_core_codex_history_observer_open`]. `thread_id`, `expected_turn_id`,
// and `prompt` must point to NUL-terminated strings. When `attachment_count`
// is nonzero, `attachments` must point to that many attachment records.
// Every record must contain NUL-terminated `name` and `path` strings and a
// declared attachment kind. `output_error`, when non-null, must be writable.
bool ward_core_codex_history_observer_steer_turn_async(struct WardCodexHistoryObserver *observer,
                                                       const char *thread_id,
                                                       const char *expected_turn_id,
                                                       const char *prompt,
                                                       const struct WardCodexTurnAttachment *attachments,
                                                       size_t attachment_count,
                                                       struct WardError **output_error);

// Selects the persisted thread observed by a Codex history observer.
//
// The first successful read is emitted immediately as an updated event.
//
// A `true` return means the command was accepted; its final outcome is
// delivered through the Codex event callback. A `false` return means
// immediate rejection, and `output_error` receives an owned error when
// non-null.
//
// # Safety
//
// `observer` must point to a live handle returned by
// [`ward_core_codex_history_observer_open`]. `thread_id` must point to a
// NUL-terminated string. `output_error`, when non-null, must be writable.
bool ward_core_codex_history_observer_watch_async(struct WardCodexHistoryObserver *observer,
                                                  const char *thread_id,
                                                  struct WardError **output_error);

// Destroys an error returned through Ward Core's private C interface.
//
// # Safety
//
// `error` must be null or a live error returned by this interface, and
// ownership may be transferred only once.
void ward_core_error_destroy(struct WardError *error);

// Returns a borrowed error message owned by `error`.
//
// # Safety
//
// `error` must be null or a live error returned by this interface.
const char *ward_core_error_message(const struct WardError *error);

// Parses source text into an owned serialized render document on the calling thread.
//
// The returned buffer is a `ward.markup.v1.Document` payload. The caller owns
// it and must destroy it with [`ward_core_owned_buffer_destroy`].
//
// # Safety
//
// `source` must point to `source_size` readable bytes when `source_size` is
// positive. The bytes must be UTF-8. `output_error`, when non-null, must be
// writable.
struct WardOwnedBuffer *ward_core_markup_parse(enum WardMarkupSourceFormat format,
                                               const uint8_t *source,
                                               size_t source_size,
                                               struct WardError **output_error);

// Returns the borrowed bytes in an owned Ward buffer.
//
// The returned pointer remains valid until the owned buffer is destroyed.
//
// # Safety
//
// `buffer` must be null or a valid live owned buffer returned by Ward Core.
const uint8_t *ward_core_owned_buffer_data(const struct WardOwnedBuffer *buffer);

// Destroys an owned Ward buffer returned directly from Ward Core.
//
// # Safety
//
// `buffer` must be null or a valid live owned buffer returned by Ward Core,
// and ownership may be transferred only once.
void ward_core_owned_buffer_destroy(struct WardOwnedBuffer *buffer);

// Returns the number of bytes in an owned Ward buffer.
//
// # Safety
//
// `buffer` must be null or a valid live owned buffer returned by Ward Core.
size_t ward_core_owned_buffer_size(const struct WardOwnedBuffer *buffer);

// Attaches a display frontend and returns its borrowed native view.
//
// Repeated calls return the same view until
// [`ward_core_realm_detach_display`] is called. The view remains owned by the
// realm and must only be wrapped, never released, by the C consumer.
//
// # Safety
//
// `realm` must point to a live handle returned by [`ward_core_realm_open`].
// This function must be called on the application's main thread.
void *ward_core_realm_attach_display(struct WardRealm *realm, struct WardError **output_error);

// Stops callbacks and destroys a realm handle.
//
// # Safety
//
// `realm` must be null or a live handle returned by
// [`ward_core_realm_open`], and ownership may be transferred only once.
void ward_core_realm_destroy(struct WardRealm *realm);

// Detaches and destroys a realm's display frontend.
//
// The C consumer must first destroy every UI wrapper around the borrowed
// native view returned by [`ward_core_realm_attach_display`].
//
// # Safety
//
// `realm` must be null or a live handle returned by
// [`ward_core_realm_open`]. This function must be called on the application's
// main thread.
void ward_core_realm_detach_display(struct WardRealm *realm);

// Queues a command to discard a stopped Realm's saved runtime state.
//
// A `true` return means the command was accepted; its final outcome is
// delivered through the Realm callback. A `false` return means immediate
// rejection, and `output_error` receives an owned error when non-null.
//
// # Safety
//
// `realm` must be null or a live handle returned by
// [`ward_core_realm_open`]. `output_error`, when non-null, must be writable.
bool ward_core_realm_discard_saved_state_async(struct WardRealm *realm, struct WardError **output_error);

// Queues a destructive stop command for a Realm.
//
// A `true` return means the command was accepted; its final outcome is
// delivered through the Realm callback. A `false` return means immediate
// rejection, and `output_error` receives an owned error when non-null.
//
// # Safety
//
// `realm` must be null or a live handle returned by
// [`ward_core_realm_open`]. `output_error`, when non-null, must be writable.
bool ward_core_realm_force_stop_async(struct WardRealm *realm, struct WardError **output_error);

// Opens an installed realm bundle without starting it.
//
// The event callback may run on any thread and may run before this function
// returns. Its borrowed event remains valid only for the duration of each
// call. The callback context must remain valid until
// [`ward_core_realm_destroy`] returns, after which no more callbacks occur. If
// this function returns null, no callback occurs after the function returns.
//
// # Safety
//
// `bundle_path` must point to a NUL-terminated string. `output_error`, when
// non-null, must be writable. The callback and its context must satisfy the
// lifetime requirements described above.
struct WardRealm *ward_core_realm_open(const char *bundle_path,
                                       WardRealmEventCallback callback,
                                       void *callback_context,
                                       struct WardError **output_error);

// Queues a pause command for a Realm.
//
// A `true` return means the command was accepted; its final outcome is
// delivered through the Realm callback. A `false` return means immediate
// rejection, and `output_error` receives an owned error when non-null.
//
// # Safety
//
// `realm` must be null or a live handle returned by
// [`ward_core_realm_open`]. `output_error`, when non-null, must be writable.
bool ward_core_realm_pause_async(struct WardRealm *realm, struct WardError **output_error);

// Queues an orderly shutdown request for a Realm guest.
//
// A `true` return means the command was accepted; its final outcome is
// delivered through the Realm callback. A `false` return means immediate
// rejection, and `output_error` receives an owned error when non-null.
//
// # Safety
//
// `realm` must be null or a live handle returned by
// [`ward_core_realm_open`]. `output_error`, when non-null, must be writable.
bool ward_core_realm_request_stop_async(struct WardRealm *realm, struct WardError **output_error);

// Queues a command to restore and resume a Realm from saved runtime state.
//
// A `true` return means the command was accepted; its final outcome is
// delivered through the Realm callback. A `false` return means immediate
// rejection, and `output_error` receives an owned error when non-null.
//
// # Safety
//
// `realm` must be null or a live handle returned by
// [`ward_core_realm_open`]. `output_error`, when non-null, must be writable.
bool ward_core_realm_restore_async(struct WardRealm *realm, struct WardError **output_error);

// Queues a resume command for a Realm.
//
// A `true` return means the command was accepted; its final outcome is
// delivered through the Realm callback. A `false` return means immediate
// rejection, and `output_error` receives an owned error when non-null.
//
// # Safety
//
// `realm` must be null or a live handle returned by
// [`ward_core_realm_open`]. `output_error`, when non-null, must be writable.
bool ward_core_realm_resume_async(struct WardRealm *realm, struct WardError **output_error);

// Queues a start command for a Realm.
//
// A `true` return means the command was accepted; its final outcome is
// delivered through the Realm callback. A `false` return means immediate
// rejection, and `output_error` receives an owned error when non-null.
//
// # Safety
//
// `realm` must be null or a live handle returned by
// [`ward_core_realm_open`]. `output_error`, when non-null, must be writable.
bool ward_core_realm_start_async(struct WardRealm *realm, struct WardError **output_error);

// Queues a command to save a Realm's runtime state and release its resources.
//
// A `true` return means the command was accepted; its final outcome is
// delivered through the Realm callback. A `false` return means immediate
// rejection, and `output_error` receives an owned error when non-null.
//
// # Safety
//
// `realm` must be null or a live handle returned by
// [`ward_core_realm_open`]. `output_error`, when non-null, must be writable.
bool ward_core_realm_suspend_async(struct WardRealm *realm, struct WardError **output_error);

// Creates the asynchronous runtime used by Ward Core handles.
//
// # Safety
//
// `output_error`, when non-null, must be writable.
struct WardRuntime *ward_core_runtime_create(struct WardError **output_error);

// Shuts down and destroys a Ward asynchronous runtime.
//
// Every handle created with this runtime must be destroyed first.
// This function must be called outside the runtime's worker threads.
//
// # Safety
//
// `runtime` must be null or a live handle returned by
// [`ward_core_runtime_create`], and ownership may be transferred only once.
void ward_core_runtime_destroy(struct WardRuntime *runtime);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* WARD_CORE_H */

// clang-format on
