// Copyright (C) 2026 Xiangsong Zeng
// SPDX-License-Identifier: GPL-3.0-or-later

use std::env;
use std::fmt;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use anyhow::{Context, Result, ensure};
use serde::Deserialize;
use toml_edit::{DocumentMut, value};

const VERSION_SYNC_COMMAND: &str = "task xtask:version:sync";

pub struct ProjectPaths {
    manifest: PathBuf,
    cargo_manifest: PathBuf,
    cmake_adapter: PathBuf,
}

impl Default for ProjectPaths {
    fn default() -> Self {
        let xtask_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let repository_dir = xtask_dir
            .parent()
            .expect("xtask must be located directly under the repository root");

        Self {
            manifest: repository_dir.join("version.toml"),
            cargo_manifest: repository_dir.join("core/Cargo.toml"),
            cmake_adapter: repository_dir.join("app/cmake/version.cmake"),
        }
    }
}

#[derive(Debug, Eq, PartialEq)]
pub struct ProductVersion {
    release: String,
    build: u64,
}

impl ProductVersion {
    fn load(path: &Path) -> Result<Self> {
        let source = fs::read_to_string(path)
            .with_context(|| format!("failed to read version manifest {}", path.display()))?;
        Self::parse(&source)
            .with_context(|| format!("failed to parse version manifest {}", path.display()))
    }

    fn parse(source: &str) -> Result<Self> {
        let manifest: VersionManifest = toml::from_str(source)?;
        ensure!(
            manifest.version == manifest.version.trim(),
            "version must not contain surrounding whitespace"
        );
        validate_release_version(&manifest.version)?;
        ensure!(manifest.build > 0, "build must be greater than zero");

        Ok(Self {
            release: manifest.version,
            build: manifest.build,
        })
    }

    fn cargo_version(&self) -> String {
        format!("{}+{}", self.release, self.build)
    }

    fn render_cmake_adapter(&self) -> String {
        format!(
            "# Generated by `{VERSION_SYNC_COMMAND}`. Do not edit directly.\n\
             set(CRAFTWARD_VERSION \"{}\")\n\
             set(CRAFTWARD_BUILD_NUMBER \"{}\")\n",
            self.release, self.build
        )
    }
}

impl fmt::Display for ProductVersion {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "{} (build {})", self.release, self.build)
    }
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct VersionManifest {
    version: String,
    build: u64,
}

pub fn sync(paths: &ProjectPaths) -> Result<ProductVersion> {
    let product = ProductVersion::load(&paths.manifest)?;
    let cargo_source = read_cargo_manifest(&paths.cargo_manifest)?;
    let cargo_source = update_cargo_manifest(&cargo_source, &product.cargo_version())?;

    write_if_changed(&paths.cargo_manifest, cargo_source.as_bytes())?;
    write_if_changed(
        &paths.cmake_adapter,
        product.render_cmake_adapter().as_bytes(),
    )?;
    run_cargo_metadata(&paths.cargo_manifest, false)?;

    Ok(product)
}

pub fn check(paths: &ProjectPaths) -> Result<ProductVersion> {
    let product = ProductVersion::load(&paths.manifest)?;
    let cargo_source = read_cargo_manifest(&paths.cargo_manifest)?;
    let actual_cargo_version = read_cargo_version(&cargo_source)?;
    let expected_cargo_version = product.cargo_version();
    ensure!(
        actual_cargo_version == expected_cargo_version,
        "{} contains workspace package version {actual_cargo_version:?}, expected \
         {expected_cargo_version:?}; run `{VERSION_SYNC_COMMAND}`",
        paths.cargo_manifest.display()
    );

    let actual_cmake_adapter = fs::read_to_string(&paths.cmake_adapter).with_context(|| {
        format!(
            "failed to read generated CMake version adapter {}; run `{VERSION_SYNC_COMMAND}`",
            paths.cmake_adapter.display()
        )
    })?;
    let expected_cmake_adapter = product.render_cmake_adapter();
    ensure!(
        actual_cmake_adapter == expected_cmake_adapter,
        "{} is out of date; run `{VERSION_SYNC_COMMAND}`",
        paths.cmake_adapter.display()
    );

    run_cargo_metadata(&paths.cargo_manifest, true)?;
    Ok(product)
}

fn validate_release_version(version: &str) -> Result<()> {
    let components: Vec<_> = version.split('.').collect();
    ensure!(
        components.len() == 3,
        "version must use major.minor.patch format"
    );

    for component in components {
        ensure!(
            !component.is_empty() && component.bytes().all(|byte| byte.is_ascii_digit()),
            "version must contain only three numeric components"
        );
        ensure!(
            component == "0" || !component.starts_with('0'),
            "version components must not contain leading zeroes"
        );
        component
            .parse::<u64>()
            .with_context(|| format!("version component {component:?} is too large"))?;
    }

    Ok(())
}

fn read_cargo_manifest(path: &Path) -> Result<String> {
    fs::read_to_string(path)
        .with_context(|| format!("failed to read Cargo manifest {}", path.display()))
}

fn parse_cargo_manifest(source: &str) -> Result<DocumentMut> {
    source
        .parse::<DocumentMut>()
        .context("failed to parse the core Cargo manifest")
}

fn read_cargo_version(source: &str) -> Result<String> {
    let document = parse_cargo_manifest(source)?;
    let version = document
        .get("workspace")
        .and_then(|item| item.as_table())
        .and_then(|workspace| workspace.get("package"))
        .and_then(|item| item.as_table())
        .and_then(|package| package.get("version"))
        .and_then(|item| item.as_str())
        .context("core Cargo manifest must define workspace.package.version as a string")?;
    Ok(version.to_owned())
}

fn update_cargo_manifest(source: &str, expected_version: &str) -> Result<String> {
    let mut document = parse_cargo_manifest(source)?;
    let version = document
        .get_mut("workspace")
        .and_then(|item| item.as_table_mut())
        .and_then(|workspace| workspace.get_mut("package"))
        .and_then(|item| item.as_table_mut())
        .and_then(|package| package.get_mut("version"))
        .context("core Cargo manifest must define workspace.package.version")?;
    let actual_version = version
        .as_str()
        .context("core Cargo manifest workspace.package.version must be a string")?;

    if actual_version != expected_version {
        *version = value(expected_version);
    }

    Ok(document.to_string())
}

fn write_if_changed(path: &Path, contents: &[u8]) -> Result<()> {
    if fs::read(path).is_ok_and(|existing| existing == contents) {
        return Ok(());
    }

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create directory {}", parent.display()))?;
    }
    fs::write(path, contents).with_context(|| format!("failed to write {}", path.display()))
}

fn run_cargo_metadata(cargo_manifest: &Path, locked: bool) -> Result<()> {
    let cargo = env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let mut command = Command::new(cargo);
    command
        .arg("metadata")
        .arg("--manifest-path")
        .arg(cargo_manifest)
        .arg("--format-version")
        .arg("1")
        .arg("--no-deps")
        .arg("--quiet")
        .stdout(Stdio::null());
    if locked {
        command.arg("--locked");
    }

    let status = command.status().with_context(|| {
        format!(
            "failed to run Cargo for version metadata in {}",
            cargo_manifest.display()
        )
    })?;
    ensure!(
        status.success(),
        "Cargo version metadata check failed for {}",
        cargo_manifest.display()
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_numeric_build_and_renders_each_build_system_version() {
        let product = ProductVersion::parse(
            r#"
version = "1.2.3"
build = 42
"#,
        )
        .unwrap();

        assert_eq!(product.release, "1.2.3");
        assert_eq!(product.build, 42);
        assert_eq!(product.cargo_version(), "1.2.3+42");
        assert!(
            product
                .render_cmake_adapter()
                .contains("set(CRAFTWARD_BUILD_NUMBER \"42\")")
        );
    }

    #[test]
    fn rejects_a_string_build_number() {
        let error = ProductVersion::parse(
            r#"
version = "1.2.3"
build = "42"
"#,
        )
        .unwrap_err();

        assert!(error.to_string().contains("invalid type"));
    }

    #[test]
    fn rejects_zero_build_number() {
        let error = ProductVersion::parse(
            r#"
version = "1.2.3"
build = 0
"#,
        )
        .unwrap_err();

        assert_eq!(error.to_string(), "build must be greater than zero");
    }

    #[test]
    fn rejects_versions_outside_the_shared_bundle_format() {
        for version in ["1.2", "1.2.3.4", "1.02.3", "1.2-beta.3"] {
            let source = format!("version = {version:?}\nbuild = 1\n");
            assert!(
                ProductVersion::parse(&source).is_err(),
                "accepted {version}"
            );
        }
    }

    #[test]
    fn updates_only_the_workspace_package_version() {
        let source = r#"[workspace]
members = []

[workspace.package]
version = "1.2.3+41"
edition = "2024"

[workspace.dependencies]
example = { version = "9" }
"#;

        let updated = update_cargo_manifest(source, "1.2.3+42").unwrap();

        assert_eq!(read_cargo_version(&updated).unwrap(), "1.2.3+42");
        assert!(updated.contains("example = { version = \"9\" }"));
        assert_eq!(
            update_cargo_manifest(&updated, "1.2.3+42").unwrap(),
            updated
        );
    }
}
